# -*- coding: utf-8 -*-
"""Tubes2_Visdat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSLTwwIUMJKZ5A8yxFPSd-3B2PkJMNbT
"""

#Import library
import pandas as pd
import numpy as np
from datetime import date, time, datetime
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
from bokeh.layouts import row, column, gridplot
from bokeh.models import HoverTool, ColumnDataSource, NumeralTickFormatter, CDSView, GroupFilter
from bokeh.models.widgets import Tabs, Panel

#Menampilkan dataset
df = pd.read_csv('./stock_market.csv')
df = df.rename(columns={"Adj Close": "AdjClose",'Name':'name','Volume':'volume','Date':'date'})
df.head()

#Melihat info data pada dataset
df.info()

#Mengubah kolom date menjadi datetime
df['date']= pd.to_datetime(df['date'])

"""#LEVEL1"""

output_notebook()

# Assign hs,nq,nk berdasarkan nama index saham
hs = df[df['name'] == 'HANG SENG']
nq = df[df['name'] == 'NASDAQ']
nk = df[df['name'] == 'NIKKEI']

# Membuat column data source pada setiap index saham
hangseng_view = ColumnDataSource(hs)
nasdaq_view = ColumnDataSource(nq)
nikkei_view = ColumnDataSource(nk)


# Membuat plot figure 
fig = figure(x_axis_type='datetime',
             plot_height=600, plot_width=1000,
             title='Perbandingan Nilai ADJ Close pada setiap index saham',
             x_axis_label='date', y_axis_label='Adj CLose')

# Plotingan setiap index saham 
fig.circle('date', 'AdjClose', color='blue', legend_label='Hang Seng', source=hangseng_view)
fig.circle('date', 'AdjClose',color='red', legend_label='Nasdaq', source=nasdaq_view)
fig.circle('date', 'AdjClose',color='orange', legend_label='Nikkei', source=nikkei_view)
fig.legend.location = 'top_right'

# menambahkan hovertool 
fig.add_tools(HoverTool(tooltips=[('Index Saham','@name'),('Adj Close', '@AdjClose'),]))
show(fig)

"""#LEVEL2"""

# Membuat tooltips 
tooltips_AdjClose = [('Name', '@name'), ('Adj Close', '$y{0.2f}')]
tooltips_Volume = [('Name', '@name'), ('Volume', '$y{0.2f}'),] 
tooltips_DayPerChange = [('Name', '@name'), ('Day Perc Change', '$y{0.2f}')] 

# Membuat figure pada masing masing tipe saham
#Figure untuk AdjClose
AdjClose_fig = figure(x_axis_type='datetime',
                 plot_height=600,plot_width=1000,
                 x_axis_label='date',y_axis_label='AdjClose',
                 tooltips = tooltips_AdjClose,
                 title='ADJ Close pada setiap index saham',)

#Figure untuk Volume
Volume_fig = figure(x_axis_type='datetime',
                    plot_height=600,plot_width=1000,
                    x_axis_label='date',y_axis_label='volume',
                    tooltips = tooltips_Volume,
                    title='Nilai Volume pada setiap index saham',)

#Volume DayPerChange
DayPerChange_fig = figure(x_axis_type='datetime',
                    plot_height=600,plot_width=1000,
                    x_axis_label='date',y_axis_label='Day_Perc_Change',
                    tooltips = tooltips_DayPerChange,
                    title='Nilai Day Percentage Change pada setiap index saham',)

# Memploting data ke dalam figure pada AdjClose
AdjClose_fig.circle('date','AdjClose',source=hangseng_view,  color='blue', legend_label='HANG SENG')
AdjClose_fig.circle('date','AdjClose',source=nasdaq_view,  color='red', legend_label='NASDAQ')
AdjClose_fig.circle('date','AdjClose',source=nikkei_view,  color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
AdjClose_fig.legend.location = 'top_right'

# show 
output_notebook()
show(AdjClose_fig)

# Memploting data ke dalam figure pada Volume
Volume_fig.circle('date','volume',source=hangseng_view ,color='blue', legend_label='HANG SENG')
Volume_fig.circle('date','volume',source=nasdaq_view ,color='red', legend_label='NASDAQ')
Volume_fig.circle('date','volume',source=nikkei_view ,color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
Volume_fig.legend.location = 'top_right'

# Show
output_notebook()
show(Volume_fig)

# Memploting data ke dalam figure pada  DayPerChange
DayPerChange_fig.circle('date','Day_Perc_Change',source=hangseng_view ,color='blue', legend_label='HANG SENG')
DayPerChange_fig.circle('date','Day_Perc_Change',source=nasdaq_view ,color='red', legend_label='NASDAQ')
DayPerChange_fig.circle('date','Day_Perc_Change',source=nikkei_view ,color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
DayPerChange_fig.legend.location = 'top_right'

# Show
output_notebook()
show(DayPerChange_fig)

#output notebook
output_notebook()

# Membuat Panel
AdjClose_panel = Panel(child=AdjClose_fig, title='Adj Close')
Volume_panel = Panel(child=Volume_fig, title='Volume')
DayPerChange_panel = Panel(child=DayPerChange_fig, title='Day Percentage Change')
tabs = Tabs(tabs=[AdjClose_panel, Volume_panel, DayPerChange_panel])

# Menampilkan hasil Panel
show(tabs)

"""#LEVEL3"""

# Memploting data ke dalam figure pada AdjClose
AdjClose_fig.circle('date','AdjClose',source=hangseng_view,  color='blue', legend_label='HANG SENG')
AdjClose_fig.circle('date','AdjClose',source=nasdaq_view,  color='red', legend_label='NASDAQ')
AdjClose_fig.circle('date','AdjClose',source=nikkei_view,  color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
AdjClose_fig.legend.location = 'top_right'

# Menyembunyikan data untuk indeks pasar saham tertentu
AdjClose_fig.legend.click_policy="hide"

# show 
output_notebook()
show(AdjClose_fig)

# Memploting data ke dalam figure pada Volume
Volume_fig.circle('date','volume',source=hangseng_view ,color='blue', legend_label='HANG SENG')
Volume_fig.circle('date','volume',source=nasdaq_view ,color='red', legend_label='NASDAQ')
Volume_fig.circle('date','volume',source=nikkei_view ,color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
Volume_fig.legend.location = 'top_right'

# Menyembunyikan data untuk indeks pasar saham tertentu
Volume_fig.legend.click_policy="hide"

# Show
output_notebook()
show(Volume_fig)

# Memploting data ke dalam figure pada  DayPerChange
DayPerChange_fig.circle('date','Day_Perc_Change',source=hangseng_view ,color='blue', legend_label='HANG SENG')
DayPerChange_fig.circle('date','Day_Perc_Change',source=nasdaq_view ,color='red', legend_label='NASDAQ')
DayPerChange_fig.circle('date','Day_Perc_Change',source=nikkei_view ,color='orange', legend_label='NIKKEI')

# Menempatkan legend ke pojok kiri atas
DayPerChange_fig.legend.location = 'top_right'

# Menyembunyikan data untuk indeks pasar saham tertentu
DayPerChange_fig.legend.click_policy="hide"

# Show
output_notebook()
show(DayPerChange_fig)

# Penambahan atribut click hide pada figure
AdjClose_fig.legend.click_policy="hide"
Volume_fig.legend.click_policy="hide"
DayPerChange_fig.legend.click_policy="hide"

# Show 
show(tabs)
